[package]
name = "iron-socket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
nix = { version = "0.27.1", features = ["socket"] }
tokio = { version = "1.32.0", features = ["full"] }
